name: 2fa

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - ".github/workflows/2fa.yml"

jobs:
  twofa:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: rsc/2fa
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - run: |
          go mod vendor
          git add -A
          git config user.email "alice@chadig.com"
          git config user.name "Alice Alchemy"
          git commit -sm "Vendor that shit homie $(git log -n 1 | head -n 1)"
          git tag -f "$(git describe --tags)"
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: 2fa
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
