name: tmux

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        curl -sfL https://gist.github.com/tessus/5e118d44261a6ab2f198/raw/5483dd982ad60c95b8582a1b184963ded95686ce/compile_tmux.sh | sed -e 's/make &&/make -j \$((\$(nproc)*4)) \&\&/g' -e 's/BASEDIR=${HOME}/BASEDIR=\${PWD}/g' -e 's/LIBEVENT_VERSION=2.0.22/LIBEVENT_VERSION=2.1.12/' -e 's/NCURSES_VERSION=6.0/NCURSES_VERSION=6.2/' | tee build.sh
        bash -xe build.sh
    - uses: "marvinpinto/action-automatic-releases@4edd7a5aabb1bc62e6dc99b3302d587bf3134e20"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "tmux"
        files: |
          work/tmux-static/local/bin/tmux

  powertop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: fenrus75/powertop
    - name: build
      run: |
        sudo apt install libpci-dev libnl-3-dev libnl-genl-3-dev gettext libgettextpo-dev autopoint gettext libncurses5-dev libncursesw5-dev libtool-bin dh-autoreconf autoconf-archive pkg-config
        ./autogen.sh
        # https://github.com/tpm2-software/tpm2-tss/blob/3d3c9a81db1354fe75dd27f5a87551c101034b0d/.ci/docker.run#L35-L37
        ./configure --disable-shared
        make -j $(($(nproc)*4))
        find .
    - uses: "marvinpinto/action-automatic-releases@4edd7a5aabb1bc62e6dc99b3302d587bf3134e20"
      if: false
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "tmux"
        files: |
          work/tmux-static/local/bin/tmux
