name: powertop

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - ".github/workflows/powertop.yml"

jobs:
  powertop:
    runs-on: ubuntu-latest
    container: debian:bookworm
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        repository: fenrus75/powertop
    - name: build
      run: |
        apt-get update -y
        apt-get install -y build-essential g++ libpci-dev libnl-3-dev libnl-genl-3-dev gettext libgettextpo-dev autopoint gettext libncurses5-dev libncursesw5-dev libtool-bin dh-autoreconf autoconf-archive pkg-config libtraceevent-dev libtracefs-dev
        ./autogen.sh
        # https://github.com/tpm2-software/tpm2-tss/blob/3d3c9a81db1354fe75dd27f5a87551c101034b0d/.ci/docker.run#L35-L37
        ./configure --disable-shared
        make -j $(($(nproc)*4))
        find .
    - uses: "marvinpinto/action-automatic-releases@4edd7a5aabb1bc62e6dc99b3302d587bf3134e20"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "powertop"
        prerelease: true
        title: "powertop"
        files: |
          src/powertop
