name: tmux

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - ".github/workflows/tmux.yml"


jobs:
  tmux:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      # contents: write
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        curl -sfL https://gist.github.com/tessus/5e118d44261a6ab2f198/raw/5483dd982ad60c95b8582a1b184963ded95686ce/compile_tmux.sh | sed -e 's/make &&/make -j \$((\$(nproc)*4)) \&\&/g' -e 's/BASEDIR=${HOME}/BASEDIR=\${PWD}/g' -e 's/LIBEVENT_VERSION=2.0.22/LIBEVENT_VERSION=2.1.12/' -e 's/NCURSES_VERSION=6.0/NCURSES_VERSION=6.2/' | tee build.sh
        bash -xe build.sh
    - uses: "marvinpinto/action-automatic-releases@4edd7a5aabb1bc62e6dc99b3302d587bf3134e20"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "tmux"
        prerelease: true
        title: "tmux"
        files: |
          work/tmux-static/local/bin/tmux
